import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Layout from "../components/Layout";
import { supabase } from "../services/supabase";
import "./Admin.css";

const Admin = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("users");

  // Stats State
  const [stats, setStats] = useState({
    totalCourses: 0,
    totalUsers: 0,
    recentCourses: [],
    allUsers: [],
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Enforce admin gateway
    const isAdmin = localStorage.getItem("isAdmin");
    if (!isAdmin) {
      navigate("/login");
      return;
    }

    const fetchAdminData = async () => {
      // Because Supabase RLS may restrict normal users, an Admin role or bypass is ideal.
      // Assuming this development database allows broad selects for the dashboard:
      const { data: courses, error } = await supabase
        .from("courses")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) {
        console.error("Failed to load admin stats", error);
        setLoading(false);
        return;
      }

      // Parse Total Courses
      const totalCourses = courses ? courses.length : 0;
      const recentCourses = courses ? courses.slice(0, 10) : [];

      // Parse Total Unique Users (extracting UUIDs from course records)
      const activeUserHashes = {};
      courses.forEach((c) => {
        if (c.user_id)
          activeUserHashes[c.user_id] = (activeUserHashes[c.user_id] || 0) + 1;
      });
      const totalUsers = Object.keys(activeUserHashes).length;

      // Map fake 'User' table elements for the demo mapping activeUserHashes
      const allUsers = Object.keys(activeUserHashes).map((uid, idx) => ({
        id: uid,
        name: `Scholar ${uid.substring(0, 5)}`,
        coursesCount: activeUserHashes[uid],
        role: idx === 0 ? "Admin" : "Student",
        status: "Active",
      }));

      setStats({
        totalCourses,
        totalUsers,
        recentCourses,
        allUsers,
      });
      setLoading(false);
    };

    fetchAdminData();
  }, [navigate]);

  return (
    <Layout activePage="admin">
      <div className="admin-page">
        {/* TOP BAR */}

        {/* STATS WIDGETS */}
        <div className="stats-row">
          <div className="stat-card">
            <div className="sc-label">Total Unique Users</div>
            <div className="sc-val" style={{ color: "var(--p1)" }}>
              {loading ? "..." : stats.totalUsers}
            </div>
            <div className="sc-trend up">Live Active Scholars</div>
          </div>
          <div className="stat-card">
            <div className="sc-label">Content Curriculums</div>
            <div className="sc-val" style={{ color: "var(--p2)" }}>
              {loading ? "..." : stats.totalCourses}
            </div>
            <div className="sc-trend up">Generated by AI</div>
          </div>
        </div>

        {/* TAB SWITCHER */}
        <div className="tab-control">
          <div
            className={`tab ${activeTab === "users" ? "active" : ""}`}
            onClick={() => setActiveTab("users")}
          >
            👥 Users
          </div>
          <div
            className={`tab ${activeTab === "content" ? "active" : ""}`}
            onClick={() => setActiveTab("content")}
          >
            📁 Content Firehose
          </div>
        </div>

        {/* DYNAMIC CONTENT VIEWS */}
        {activeTab === "users" && (
          <div className="admin-section fade-in">
            <div className="sec-title">Global User Roster</div>
            <div className="table-box">
              <table>
                <thead>
                  <tr>
                    <th>UserID</th>
                    <th>Role</th>
                    <th>Lifelong Courses</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {stats.allUsers.map((u, i) => (
                    <tr key={i}>
                      <td>
                        <strong>{u.name}</strong>
                        <br />
                        <span
                          style={{ color: "var(--muted)", fontSize: "0.8em" }}
                        >
                          {u.id}
                        </span>
                      </td>
                      <td>
                        <span
                          className={`badge ${u.role === "Admin" ? "b-admin" : "b-student"}`}
                        >
                          {u.role}
                        </span>
                      </td>
                      <td>{u.coursesCount} generated</td>
                      <td>
                        <span className="badge b-active">{u.status}</span>
                      </td>
                      <td>
                        <button className="action-btn">Inspect</button>
                        {u.role !== "Admin" && (
                          <button className="action-btn danger">Ban</button>
                        )}
                      </td>
                    </tr>
                  ))}
                  {stats.allUsers.length === 0 && !loading && (
                    <tr>
                      <td
                        colSpan="5"
                        style={{ textAlign: "center", padding: "20px" }}
                      >
                        No users detected in Database.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {activeTab === "content" && (
          <div className="admin-section fade-in">
            <div className="sec-title">Recent Generations</div>
            <div className="table-box">
              <table>
                <thead>
                  <tr>
                    <th>Course Core Topic</th>
                    <th>Level Assigned</th>
                    <th>Modules Built</th>
                    <th>Owner ID</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {stats.recentCourses.map((c, i) => (
                    <tr key={i}>
                      <td>
                        <strong>{c.topic}</strong>
                      </td>
                      <td>{c.level || "Beginner"}</td>
                      <td>{c.content?.modules?.length || 0}</td>
                      <td>
                        <span
                          style={{ color: "var(--muted)", fontSize: "0.85em" }}
                        >
                          {c.user_id?.substring(0, 8)}...
                        </span>
                      </td>
                      <td>
                        <button
                          className="action-btn"
                          onClick={() => navigate(`/course/${c.id}`)}
                        >
                          Open
                        </button>
                        <button className="action-btn danger">Prune</button>
                      </td>
                    </tr>
                  ))}
                  {stats.recentCourses.length === 0 && !loading && (
                    <tr>
                      <td
                        colSpan="5"
                        style={{ textAlign: "center", padding: "20px" }}
                      >
                        No content generated recently.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
};

export default Admin;
